main:circle.o graph.o rectangle.o pptpage.o circlerect.o main.cpp
	g++ circle.o graph.o rectangle.o pptpage.o circlerect.o main.cpp -o main
circle.o:circle.cpp
	g++ -c circle.cpp
rectangle.o:rectangle.cpp
	g++ -c rectangle.cpp
graph.o:graph.cpp
	g++ -c graph.cpp
circlerect.o:circlerect.cpp
	g++ -c circlerect.cpp
pptpage.o:pptpage.cpp
	g++ -c pptpage.cpp

